#include <bits/stdc++.h>

using namespace std;

int main() {
	//creating a list of items
	vector<int> items = {7, 1, 12, 5};
	const int n = items.size();
	

	//all subsets consist of the following choice
	//	picking a number or not picking a number
	//we can define this through a boolean "string" of choices
	//	110101001
	//where each choice represents whether we picked the item
	//or didn't pick the item
	//
	//this will give us 2^n different possible permutations of
	//items
	//
	//and we can generate each of these items by generating all
	//permutations of 1s and 0s
	//
	//all the permutations of 1s and 0s can be generated by
	//incrementing a number and reading its binary form.
	//
	//this can be implemented as follows
		
	for(int b = 0; b < (1<<n); b++){
		vector<int> subset;
		for(int i = 0; i < n; i++)
			if(b&(1<<i)) subset.push_back(items[i]);
		/*
		for(int i = 0; i < subset.size(); i++)
			cout << subset[i] << ' ';
		cout << endl;
		*/
	}
}
